# Generated by Django 5.2.18 on 2026-10-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneApplicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(default='ANNCSU', max_length=150, verbose_name='Nome applicazione')),
                ('titolo_browser', models.CharField(default='ANNCSU', max_length=200, verbose_name='Titolo browser')),
                ('intestazione', models.CharField(default='Consultazione ANNCSU', max_length=250, verbose_name='Intestazione')),
                ('sottotitolo', models.CharField(blank=True, default='', max_length=500, verbose_name='Sottotitolo')),
                ('footer', models.CharField(blank=True, default='', max_length=500, verbose_name='Footer')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('attiva', models.BooleanField(default=True, verbose_name='Configurazione attiva')),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione applicazione',
                'verbose_name_plural': 'Configurazione applicazione',
            },
        ),
    ]
