# Generated by Django 5.2.18 on 2026-10-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazionePDND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False, verbose_name='Configurazione attiva')),
                ('client_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Client ID')),
                ('purpose_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Purpose ID')),
                ('kid', models.CharField(blank=True, default='', max_length=200, verbose_name='Key ID (kid)')),
                ('iss', models.CharField(blank=True, default='', help_text='Normalmente coincide con il client_id.', max_length=200, verbose_name='Issuer (iss)')),
                ('sub', models.CharField(blank=True, default='', help_text='Normalmente coincide con il client_id.', max_length=200, verbose_name='Subject (sub)')),
                ('audience_assertion', models.CharField(default='auth.interop.pagopa.it/client-assertion', max_length=500, verbose_name='Audience client assertion')),
                ('url_token', models.URLField(default='https://auth.interop.pagopa.it/token.oauth2', max_length=500, verbose_name='URL token PDND')),
                ('audience_eservice', models.CharField(blank=True, default='', max_length=500, verbose_name='Audience e-service')),
                ('base_url_eservice', models.URLField(default='https://modipa.agenziaentrate.gov.it/govway/rest/in/AgenziaEntrate-PDND/anncsu-consultazione/v1', max_length=500, verbose_name='Base URL e-service ANNCSU')),
                ('percorso_chiave_privata', models.CharField(default='/run/secrets/pdnd_private_key.pem', max_length=500, verbose_name='Percorso chiave privata')),
                ('algoritmo_jwt', models.CharField(default='RS256', max_length=20, verbose_name='Algoritmo JWT')),
                ('tipo_jwt', models.CharField(default='JWT', max_length=20, verbose_name='Tipo JWT')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout chiamate')),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione PDND',
                'verbose_name_plural': 'Configurazione PDND',
            },
        ),
        migrations.AddField(
            model_name='configurazioneapplicazione',
            name='codice_belfiore_default',
            field=models.CharField(blank=True, default='', help_text='Codice Belfiore proposto automaticamente nelle ricerche.', max_length=4, verbose_name='Codice Belfiore predefinito'),
        ),
    ]
