# Generated by Django 5.2.18 on 2026-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configurazionepdnd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheANNCSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accessi', 'Elenco completo accessi'), ('accesso', 'Dettaglio accesso')], db_index=True, max_length=30)),
                ('chiave', models.CharField(max_length=255, unique=True)),
                ('richiesta_json', models.JSONField(blank=True, default=dict)),
                ('risposta_json', models.JSONField()),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('scade_il', models.DateTimeField(db_index=True)),
                ('ultimo_accesso', models.DateTimeField(blank=True, null=True)),
                ('numero_hit', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cache ANNCSU',
                'verbose_name_plural': 'Cache ANNCSU',
                'ordering': ('-aggiornata_il',),
            },
        ),
    ]
