# Generated by Django 5.2.18 on 2026-10-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cacheanncsu'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionepdnd',
            name='cache_accessi_ore',
            field=models.PositiveSmallIntegerField(default=24, help_text="Durata della cache dell'elenco completo degli accessi di una via.", verbose_name='Cache elenco accessi (ore)'),
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='cache_dettaglio_accesso_ore',
            field=models.PositiveSmallIntegerField(default=24, help_text='Durata della cache del dettaglio di un singolo accesso.', verbose_name='Cache dettaglio accesso (ore)'),
        ),
    ]
