# Generated by Django 5.2.18 on 2026-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configurazionepdnd_cache_accessi_ore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoreRichiesteANNCSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField(db_index=True, unique=True, verbose_name='Giorno')),
                ('richieste', models.PositiveIntegerField(default=0, verbose_name='Richieste effettuate')),
                ('ultima_richiesta', models.DateTimeField(blank=True, null=True, verbose_name='Ultima richiesta')),
            ],
            options={
                'verbose_name': 'Contatore richieste ANNCSU',
                'verbose_name_plural': 'Contatori richieste ANNCSU',
                'ordering': ('-giorno',),
            },
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='limite_richieste_giornaliere',
            field=models.PositiveIntegerField(default=100, help_text="Limite giornaliero previsto dall'e-service ANNCSU. Utilizzato esclusivamente per il contatore informativo.", verbose_name='Limite richieste ANNCSU giornaliere'),
        ),
    ]
