# Generated by Django 5.2.18 on 2026-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contatorerichiesteanncsu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheanncsu',
            name='tipo',
            field=models.CharField(choices=[('odonimi', 'Ricerca odonimi'), ('area', 'Dettaglio area'), ('accessi', 'Elenco completo accessi'), ('accesso', 'Dettaglio accesso')], db_index=True, max_length=30),
        ),
    ]
